using GrowIt.Application.Common.Exceptions;
using GrowIt.Application.TrainingPlans.Commands.CreateTrainingPlan;
using GrowIt.Application.Workouts.Commands.AddExerciseToWorkout;
using GrowIt.Application.Workouts.Commands.LogSet;
using GrowIt.Domain.Entities;
using GrowIt.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;

namespace GrowIt.Integration.Tests;

/// Ids are generated by the client so a write can be composed offline and retried until
/// it lands. That makes two things load-bearing: replaying a create must not duplicate
/// anything, and an id must never let one user write into another's rows.
public class IdempotentCreateTests : IAsyncLifetime
{
    private const string ConnectionString =
        "Host=localhost;Port=5432;Database=growit;Username=growit;Password=localdev";

    private static readonly Guid BenchPress = Guid.Parse("a1b2c3d4-0001-0000-0000-000000000000");

    private readonly Guid _userId = Guid.CreateVersion7();
    private readonly Guid _strangerId = Guid.CreateVersion7();

    private readonly List<Guid> _planIds = [];
    private readonly List<Guid> _workoutIds = [];

    private static GrowItDbContext NewContext() =>
        new(new DbContextOptionsBuilder<GrowItDbContext>().UseNpgsql(ConnectionString).Options);

    public Task InitializeAsync() => Task.CompletedTask;

    public async Task DisposeAsync()
    {
        await using var db = NewContext();

        var workouts = await db.Workouts.Where(w => _workoutIds.Contains(w.Id)).ToListAsync();
        db.Workouts.RemoveRange(workouts);

        var plans = await db.TrainingPlans.Where(p => _planIds.Contains(p.Id)).ToListAsync();
        db.TrainingPlans.RemoveRange(plans);

        await db.SaveChangesAsync();
    }

    private async Task<Guid> CreatePlanAsync(Guid id, Guid ownerId)
    {
        _planIds.Add(id);

        await using var db = NewContext();
        var handler = new CreateTrainingPlanCommandHandler(db);
        return await handler.Handle(
            new CreateTrainingPlanCommand(id, ownerId, "Plan", null), CancellationToken.None);
    }

    /// A session with one exercise on it, owned by whoever is named.
    private async Task<Guid> SeedWorkoutExerciseAsync(Guid ownerId)
    {
        var workoutId = Guid.CreateVersion7();
        var workoutExerciseId = Guid.CreateVersion7();
        _workoutIds.Add(workoutId);

        await using var db = NewContext();
        db.Workouts.Add(new Workout
        {
            Id = workoutId,
            UserId = ownerId,
            Name = "Session",
            PerformedAt = DateOnly.FromDateTime(DateTime.UtcNow),
            CreatedAt = DateTime.UtcNow,
            WorkoutExercises =
            {
                new WorkoutExercise { Id = workoutExerciseId, ExerciseId = BenchPress, OrderIndex = 0 }
            }
        });

        await db.SaveChangesAsync();
        return workoutExerciseId;
    }

    [Fact]
    public async Task Replaying_a_create_leaves_a_single_row()
    {
        var planId = Guid.CreateVersion7();

        var first = await CreatePlanAsync(planId, _userId);
        // The response to the first attempt never made it back, so the queue sends again.
        var second = await CreatePlanAsync(planId, _userId);

        Assert.Equal(planId, first);
        Assert.Equal(planId, second);

        await using var db = NewContext();
        Assert.Equal(1, await db.TrainingPlans.CountAsync(p => p.Id == planId));
    }

    [Fact]
    public async Task Replaying_a_create_does_not_overwrite_what_is_there()
    {
        var planId = Guid.CreateVersion7();
        await CreatePlanAsync(planId, _userId);

        await using (var db = NewContext())
        {
            var plan = await db.TrainingPlans.FirstAsync(p => p.Id == planId);
            plan.Name = "Renamed since";
            await db.SaveChangesAsync();
        }

        // The retry carries the original payload. Applying it would silently undo an
        // edit the user has already made, so a replay has to be a no-op.
        await CreatePlanAsync(planId, _userId);

        await using var check = NewContext();
        var stored = await check.TrainingPlans.FirstAsync(p => p.Id == planId);
        Assert.Equal("Renamed since", stored.Name);
    }

    [Fact]
    public async Task An_id_that_belongs_to_someone_else_is_refused()
    {
        var planId = Guid.CreateVersion7();
        await CreatePlanAsync(planId, _strangerId);

        await Assert.ThrowsAsync<ConflictException>(() => CreatePlanAsync(planId, _userId));

        // The stranger keeps their plan.
        await using var db = NewContext();
        var stored = await db.TrainingPlans.FirstAsync(p => p.Id == planId);
        Assert.Equal(_strangerId, stored.UserId);
    }

    [Fact]
    public async Task Logging_the_same_set_twice_leaves_one_row()
    {
        var workoutExerciseId = await SeedWorkoutExerciseAsync(_userId);
        var setId = Guid.CreateVersion7();

        var command = new LogSetCommand(setId, _userId, workoutExerciseId, 100m, 5, 0);

        await using (var db = NewContext())
        {
            await new LogSetCommandHandler(db).Handle(command, CancellationToken.None);
        }

        // Logged in a basement with no signal: the write is retried when signal returns.
        await using (var db = NewContext())
        {
            await new LogSetCommandHandler(db).Handle(command, CancellationToken.None);
        }

        await using var check = NewContext();
        Assert.Equal(1, await check.Sets.CountAsync(s => s.Id == setId));
    }

    [Fact]
    public async Task A_set_keeps_the_position_the_client_gave_it()
    {
        var workoutExerciseId = await SeedWorkoutExerciseAsync(_userId);

        await using (var db = NewContext())
        {
            var handler = new LogSetCommandHandler(db);
            await handler.Handle(
                new LogSetCommand(Guid.CreateVersion7(), _userId, workoutExerciseId, 100m, 5, 0),
                CancellationToken.None);
        }

        await using (var db = NewContext())
        {
            var handler = new LogSetCommandHandler(db);
            await handler.Handle(
                new LogSetCommand(Guid.CreateVersion7(), _userId, workoutExerciseId, 105m, 3, 1),
                CancellationToken.None);
        }

        await using var check = NewContext();
        var sets = await check.Sets
            .Where(s => s.WorkoutExerciseId == workoutExerciseId)
            .OrderBy(s => s.OrderIndex)
            .ToListAsync();

        // OrderIndex used to be hardcoded to 0, which left every set claiming to be first.
        Assert.Equal(new[] { 0, 1 }, sets.Select(s => s.OrderIndex));
        Assert.Equal(new[] { 100m, 105m }, sets.Select(s => s.WeightKg));
    }

    [Fact]
    public async Task A_set_cannot_be_logged_into_someone_elses_workout()
    {
        var strangersExerciseId = await SeedWorkoutExerciseAsync(_strangerId);

        await using var db = NewContext();
        var handler = new LogSetCommandHandler(db);

        await Assert.ThrowsAsync<NotFoundException>(() => handler.Handle(
            new LogSetCommand(Guid.CreateVersion7(), _userId, strangersExerciseId, 100m, 5, 0),
            CancellationToken.None));

        await using var check = NewContext();
        Assert.Equal(0, await check.Sets.CountAsync(s => s.WorkoutExerciseId == strangersExerciseId));
    }

    [Fact]
    public async Task An_exercise_cannot_be_added_to_someone_elses_workout()
    {
        var strangersExerciseId = await SeedWorkoutExerciseAsync(_strangerId);

        await using var db = NewContext();
        var strangersWorkoutId = await db.WorkoutExercises
            .Where(e => e.Id == strangersExerciseId)
            .Select(e => e.WorkoutId)
            .FirstAsync();

        var handler = new AddExerciseToWorkoutHandler(db);

        await Assert.ThrowsAsync<NotFoundException>(() => handler.Handle(
            new AddExerciseToWorkoutCommand(
                Guid.CreateVersion7(), _userId, strangersWorkoutId, BenchPress, 1, null, null, null),
            CancellationToken.None));
    }
}
